### ISSUE TITLE
`Promise` is not defined in IE

### ISSUE THREAD

**Issue by nick-herrera** [EditLLC/javascript-montage#13]
The `javascript-montage` wrapper is unusable in all versions of Internet Explorer since `Promise` is undefined. `Promise` works as expected in Microsoft Edge.

**Comment by zackify** [comment]
You can just use https://babeljs.io/docs/usage/polyfill/

**Comment by nick-herrera** [comment]
Thanks @zackify

**Comment by zackify** [comment]
np!!
